name: remagine
description: A Flutter app that generates images using the Imagine.art API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^4.0.4
  http: ^0.13.5
  lottie: ^2.3.2
  provider: ^6.0.5
  share_plus: ^7.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - .env
